#!/usr/bin/python2.7
import os
import sys
from oslocfg import cfg
from seafutil import config
from seafutil.ccnet import CcnetCommand

CONF = cfg.CONF



def main():
    if os.getuid() != 0:
        sys.stderr.write('Init script run user not root\n')
        sys.stderr.flush()
        sys.exit(1)

    CONF.register_cli_opts(config.location_opts)
    CONF.register_cli_opts(config.base_init_opts)
    CONF.register_cli_opts(config.ccnet_opts)
    CONF.register_cli_opts(config.ccnet_init_opts)
    CONF.register_cli_opts(config.database_init_opts)
    CONF(project='seafile-init-ccnet', default_config_files=['/etc/seafile.conf', ])

    initParser = CcnetCommand()
    with initParser.generate_conf():
        initParser.execute()

if __name__ == '__main__':
    main()