#!/usr/bin/python2.7
import os
import sys
from oslocfg import cfg
from seafutil import config
from seafutil.seahub import SeahubCommand

CONF = cfg.CONF


def main():
    if os.getuid() != 0:
        sys.stderr.write('Init script run user not root\n')
        sys.stderr.flush()
        sys.exit(1)
    CONF.register_cli_opts(config.location_opts)
    CONF.register_cli_opts(config.base_init_opts)
    CONF.register_cli_opts(config.seahub_opts)
    CONF.register_cli_opts(config.seahub_init_opts)
    CONF.register_cli_opts(config.database_init_opts)
    CONF(project='seafile-init-seahub', default_config_files=['/etc/seafile.conf', ])
    initParser = SeahubCommand()
    with initParser.generate_conf():
        initParser.execute()

    thirdpart = os.path.join(CONF.seahub, 'thirdpart')
    if CONF.memcache:
        print("######################################")
        print("tar -xf /usr/share/doc/python2-seafutil/pylibmc.tar -C %s" % thirdpart)


if __name__ == '__main__':
    main()